// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPUuHt9zbWtqmFOKmxfiH5wsYh5IdA0_w',
    appId: '1:409850017205:web:3379b4ae17ecef748455fc',
    messagingSenderId: '409850017205',
    projectId: 'recipelib-18e85',
    authDomain: 'recipelib-18e85.firebaseapp.com',
    storageBucket: 'recipelib-18e85.appspot.com',
    measurementId: 'G-XDYRHCJX71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBG8hRynwzTIRChSbK1SvpHoEq2Tz-UA8',
    appId: '1:409850017205:android:a8d8524fdbb193878455fc',
    messagingSenderId: '409850017205',
    projectId: 'recipelib-18e85',
    storageBucket: 'recipelib-18e85.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyAWpwUUaNve3dw_agKUOgkWD3YQ7ElUI',
    appId: '1:409850017205:ios:28f655b56a6765b58455fc',
    messagingSenderId: '409850017205',
    projectId: 'recipelib-18e85',
    storageBucket: 'recipelib-18e85.appspot.com',
    iosBundleId: 'com.example.pambeAcIfa.RunnerTests',
  );
}
